services:
  - type: web
    name: sehhaty-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app --workers 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: sehhaty-db
          property: connectionString
    autoDeploy: false

databases:
  - name: sehhaty-db
    databaseName: sehhaty
    user: sehhaty_user
    plan: free

